/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author rocio
 */
public class MateriaVista extends javax.swing.JFrame {

    /**
     * Creates new form Materia
     */
    public MateriaVista() {
        initComponents();
    }




    public JButton getjBGuardar() {
        return jBGuardar;
    }

    public void setjBGuardar(JButton jBGuardar) {
        this.jBGuardar = jBGuardar;
    }

    public JButton getjBVolver() {
        return jBVolver;
    }


    public JComboBox<String> getjCBDNIProfesor() {
        return jCBDNIProfesor;
    }

    public void setjCBDNIProfesor(JComboBox<String> jCBDNIProfesor) {
        this.jCBDNIProfesor = jCBDNIProfesor;
    }

    public JTextField getjTCargaHoraria() {
        return jTCargaHoraria;
    }

    public void setjTCargaHoraria(JTextField jTCargaHoraria) {
        this.jTCargaHoraria = jTCargaHoraria;
    }

    public JTextField getjTNombre() {
        return jTNombre;
    }

    public void setjTNombre(JTextField jTNombre) {
        this.jTNombre = jTNombre;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JButton getjBEliminar() {
        return jBEliminar;
    }

    public JButton getjBModificar() {
        return jBModificar;
    }

    public void setjTCodigo(JTextField jTCodigo) {
        this.jTCodigo = jTCodigo;
    }

    public JTextField getjTCodigo() {
        return jTCodigo;
    }

    public JTextField getjTProfesorNombre() {
        return jTProfesorNombre;
    }

    public void setjTProfesorNombre(JTextField jTProfesorNombre) {
        this.jTProfesorNombre = jTProfesorNombre;
    }

    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLMateriaTitulo = new javax.swing.JLabel();
        jLNombreTitulo = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jCargaHorariaTitulo = new javax.swing.JLabel();
        jTCargaHoraria = new javax.swing.JTextField();
        jLDNIProfesorTitulo = new javax.swing.JLabel();
        jCBDNIProfesor = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBGuardar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jLCodigoTitulo = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jTProfesorNombre = new javax.swing.JTextField();
        jLNombreProf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 154, 151));

        jLMateriaTitulo.setFont(new java.awt.Font("Ubuntu Medium", 1, 24)); // NOI18N
        jLMateriaTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLMateriaTitulo.setText("MATERIA");

        jLNombreTitulo.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLNombreTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLNombreTitulo.setText("NOMBRE");

        jTNombre.setBackground(new java.awt.Color(255, 253, 232));
        jTNombre.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N

        jCargaHorariaTitulo.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jCargaHorariaTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jCargaHorariaTitulo.setText("CARGA HORARIA");

        jTCargaHoraria.setBackground(new java.awt.Color(255, 253, 232));
        jTCargaHoraria.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N

        jLDNIProfesorTitulo.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLDNIProfesorTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLDNIProfesorTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLDNIProfesorTitulo.setText("DNI PROFESOR");

        jCBDNIProfesor.setBackground(new java.awt.Color(255, 253, 232));
        jCBDNIProfesor.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jCBDNIProfesor.setForeground(new java.awt.Color(51, 51, 51));

        jTable1.setBackground(new java.awt.Color(255, 253, 232));
        jTable1.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(21, 205, 168));
        jScrollPane1.setViewportView(jTable1);

        jBGuardar.setBackground(new java.awt.Color(21, 205, 168));
        jBGuardar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jBGuardar.setText("NUEVO");

        jBVolver.setBackground(new java.awt.Color(21, 205, 168));
        jBVolver.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(51, 51, 51));
        jBVolver.setText("VOLVER");

        jBEliminar.setBackground(new java.awt.Color(21, 205, 168));
        jBEliminar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(51, 51, 51));
        jBEliminar.setText("ELIMINAR");

        jBModificar.setBackground(new java.awt.Color(21, 205, 168));
        jBModificar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(51, 51, 51));
        jBModificar.setText("MODIFICAR");

        jLCodigoTitulo.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLCodigoTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLCodigoTitulo.setText("CODIGO");

        jTCodigo.setBackground(new java.awt.Color(255, 253, 232));
        jTCodigo.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N

        jTProfesorNombre.setBackground(new java.awt.Color(255, 253, 232));
        jTProfesorNombre.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N

        jLNombreProf.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLNombreProf.setForeground(new java.awt.Color(241, 228, 228));
        jLNombreProf.setText("NOMBRE PROFESOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLMateriaTitulo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jCargaHorariaTitulo)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLCodigoTitulo)
                                            .addComponent(jLNombreTitulo)))
                                    .addComponent(jLDNIProfesorTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLNombreProf, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCargaHoraria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCBDNIProfesor, javax.swing.GroupLayout.Alignment.LEADING, 0, 219, Short.MAX_VALUE)
                                    .addComponent(jTProfesorNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTCodigo)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBVolver)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jBModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLMateriaTitulo)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCodigoTitulo))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNombreTitulo)
                            .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCargaHorariaTitulo)
                            .addComponent(jTCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLDNIProfesorTitulo)
                            .addComponent(jCBDNIProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTProfesorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNombreProf))
                        .addGap(23, 23, 23)
                        .addComponent(jBGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBEliminar)
                        .addGap(13, 13, 13)
                        .addComponent(jBModificar)
                        .addGap(18, 18, 18)
                        .addComponent(jBVolver)))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<String> jCBDNIProfesor;
    private javax.swing.JLabel jCargaHorariaTitulo;
    private javax.swing.JLabel jLCodigoTitulo;
    private javax.swing.JLabel jLDNIProfesorTitulo;
    private javax.swing.JLabel jLMateriaTitulo;
    private javax.swing.JLabel jLNombreProf;
    private javax.swing.JLabel jLNombreTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCargaHoraria;
    private javax.swing.JTextField jTCodigo;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTProfesorNombre;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
