/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author rocio
 */
public class NotaVista extends javax.swing.JFrame {

    /**
     * Creates new form Notas
     */
    public NotaVista() {
        initComponents();
    }

    public JTable getjTNotas() {
        return jTNotas;
    }

    public void setjTNotas(JTable jTNotas) {
        this.jTNotas = jTNotas;
    }

    public JComboBox<String> getjCBDniAlumno() {
        return jCBDniAlumno;
    }

    public void setjCBDniAlumno(JComboBox<String> jCBDniAlumno) {
        this.jCBDniAlumno = jCBDniAlumno;
    }

    public JComboBox<String> getjCBCodigoMateria() {
        return jCBCodigoMateria;
    }

    public void setjCBCodigoMateria(JComboBox<String> jCBCodigoMateria) {
        this.jCBCodigoMateria = jCBCodigoMateria;
    }

    public JTextField getjTNota() {
        return jTNota;
    }

    public void setjTNota(JTextField jTNota) {
        this.jTNota = jTNota;
    }

    public JButton getjBGuardar() {
        return jBGuardar;
    }

    public JButton getjBEliminar() {
        return jBEliminar;
    }

    public JButton getjBModificar() {
        return jBModificar;
    }

    public JButton getjBVolver() {
        return jBVolver;
    }

    public JTextField getjTMateria() {
        return jTMateria;
    }

    public void setjTMateria(JTextField jTMateria) {
        this.jTMateria = jTMateria;
    }

    public JTextField getjTAlumno() {
        return jTAlumno;
    }

    public void setjTAlumno(JTextField jTAlumno) {
        this.jTAlumno = jTAlumno;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLNotasTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTNotas = new javax.swing.JTable();
        jLAlumnoTitulo = new javax.swing.JLabel();
        jCBDniAlumno = new javax.swing.JComboBox<>();
        jLMateriaTitulo = new javax.swing.JLabel();
        jCBCodigoMateria = new javax.swing.JComboBox<>();
        jLNotaTitulo = new javax.swing.JLabel();
        jTNota = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBVolver = new javax.swing.JButton();
        jTMateria = new javax.swing.JTextField();
        jTAlumno = new javax.swing.JTextField();
        jLNombreAlumno = new javax.swing.JLabel();
        jLNombreMateria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(9, 154, 151));

        jLNotasTitulo.setFont(new java.awt.Font("Ubuntu Medium", 1, 24)); // NOI18N
        jLNotasTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLNotasTitulo.setText("NOTAS");

        jTNotas.setBackground(new java.awt.Color(255, 253, 232));
        jTNotas.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jTNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTNotas.setGridColor(new java.awt.Color(21, 205, 168));
        jScrollPane1.setViewportView(jTNotas);

        jLAlumnoTitulo.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLAlumnoTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLAlumnoTitulo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLAlumnoTitulo.setText("ALUMNO DNI");

        jCBDniAlumno.setBackground(new java.awt.Color(255, 253, 232));
        jCBDniAlumno.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jCBDniAlumno.setForeground(new java.awt.Color(51, 51, 51));

        jLMateriaTitulo.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLMateriaTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLMateriaTitulo.setText("MATERIA CODIGO");

        jCBCodigoMateria.setBackground(new java.awt.Color(255, 253, 232));
        jCBCodigoMateria.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jCBCodigoMateria.setForeground(new java.awt.Color(51, 51, 51));

        jLNotaTitulo.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLNotaTitulo.setForeground(new java.awt.Color(241, 228, 228));
        jLNotaTitulo.setText("NOTA");

        jTNota.setBackground(new java.awt.Color(255, 253, 232));
        jTNota.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N
        jTNota.setForeground(new java.awt.Color(51, 51, 51));

        jBGuardar.setBackground(new java.awt.Color(21, 205, 168));
        jBGuardar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jBGuardar.setText("NUEVO");

        jBEliminar.setBackground(new java.awt.Color(21, 205, 168));
        jBEliminar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(51, 51, 51));
        jBEliminar.setText("ELIMINAR");

        jBModificar.setBackground(new java.awt.Color(21, 205, 168));
        jBModificar.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBModificar.setForeground(new java.awt.Color(51, 51, 51));
        jBModificar.setText("MODIFICAR");

        jBVolver.setBackground(new java.awt.Color(21, 205, 168));
        jBVolver.setFont(new java.awt.Font("Ubuntu Light", 0, 12)); // NOI18N
        jBVolver.setForeground(new java.awt.Color(51, 51, 51));
        jBVolver.setText("VOLVER");

        jTMateria.setBackground(new java.awt.Color(255, 253, 232));
        jTMateria.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N

        jTAlumno.setBackground(new java.awt.Color(255, 253, 232));
        jTAlumno.setFont(new java.awt.Font("Ubuntu", 0, 11)); // NOI18N

        jLNombreAlumno.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLNombreAlumno.setForeground(new java.awt.Color(241, 228, 228));
        jLNombreAlumno.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLNombreAlumno.setText("ALUMNO NOMBRE");

        jLNombreMateria.setFont(new java.awt.Font("Ubuntu Medium", 0, 12)); // NOI18N
        jLNombreMateria.setForeground(new java.awt.Color(241, 228, 228));
        jLNombreMateria.setText("MATERIA NOMBRE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLNotasTitulo)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLAlumnoTitulo)
                                            .addComponent(jLNombreAlumno))
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTAlumno)
                                            .addComponent(jCBDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLMateriaTitulo)
                                        .addComponent(jLNombreMateria)
                                        .addComponent(jLNotaTitulo))
                                    .addGap(35, 35, 35)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTMateria)
                                        .addComponent(jCBCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jTNota, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBVolver, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLNotasTitulo)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLAlumnoTitulo)
                            .addComponent(jCBDniAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNombreAlumno))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLMateriaTitulo)
                            .addComponent(jCBCodigoMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNombreMateria))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLNotaTitulo)
                            .addComponent(jTNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jBGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBEliminar)
                        .addGap(9, 9, 9)
                        .addComponent(jBModificar)
                        .addGap(39, 39, 39)
                        .addComponent(jBVolver)))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBVolver;
    private javax.swing.JComboBox<String> jCBCodigoMateria;
    private javax.swing.JComboBox<String> jCBDniAlumno;
    private javax.swing.JLabel jLAlumnoTitulo;
    private javax.swing.JLabel jLMateriaTitulo;
    private javax.swing.JLabel jLNombreAlumno;
    private javax.swing.JLabel jLNombreMateria;
    private javax.swing.JLabel jLNotaTitulo;
    private javax.swing.JLabel jLNotasTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTAlumno;
    private javax.swing.JTextField jTMateria;
    private javax.swing.JTextField jTNota;
    private javax.swing.JTable jTNotas;
    // End of variables declaration//GEN-END:variables
}
