/*
 * menu_inicio.java
 *
 * Created on 26 de agosto de 2009, 09:50
 */

package vista;

/**
 *
 * @author  0535
 */
public class menu_inicio extends javax.swing.JFrame {

    /** Creates new form menu_inicio */
    public menu_inicio() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAdminPersonas = new javax.swing.JToggleButton();
        btAdminPerfiles = new javax.swing.JButton();
        btAdminUsuarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btAdminPersonas.setText("Administrar Personas");
        btAdminPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdminPersonasActionPerformed(evt);
            }
        });

        btAdminPerfiles.setText("Administrar Perfiles");
        btAdminPerfiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdminPerfilesActionPerformed(evt);
            }
        });

        btAdminUsuarios.setText("Administrar Usuarios");
        btAdminUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdminUsuariosActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btAdminUsuarios, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(btAdminPersonas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 171, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btAdminPerfiles, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, btAdminPerfiles, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, btAdminPersonas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btAdminUsuarios)
                .add(102, 102, 102))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btAdminPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdminPersonasActionPerformed
// TODO add your handling code here:
    new persona_lista().setVisible(true);
}//GEN-LAST:event_btAdminPersonasActionPerformed

private void btAdminPerfilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdminPerfilesActionPerformed
// TODO add your handling code here:
    new perfil_lista_admin().setVisible(true);
}//GEN-LAST:event_btAdminPerfilesActionPerformed

private void btAdminUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdminUsuariosActionPerformed
// TODO add your handling code here:
    new usuario_lista().setVisible(true);
}//GEN-LAST:event_btAdminUsuariosActionPerformed

    /**
    * @param args the command line arguments
    */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdminPerfiles;
    private javax.swing.JToggleButton btAdminPersonas;
    private javax.swing.JButton btAdminUsuarios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
