/*
 * perfil_explorer.java
 *
 * Created on 25 de agosto de 2009, 12:27
 */
package vista;

import controlador.GestorPerfil;
import controlador.GestorTabla;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import modelo.Perfil;

/**
 *
 * @author  0535
 */
public class perfil_explorer extends javax.swing.JFrame {

    private DefaultTableModel listaPerfiles;
    private usuario_admin usuarioAdmin;

    /** Creates new form perfil_explorer */
    public perfil_explorer() {
        initComponents();
    }

    perfil_explorer(usuario_admin usuarioAdmin) {
        this.usuarioAdmin = usuarioAdmin;
        try {
            initComponents();
            //configuro el encabezado de la tabla
            configTabla();
            //modelo = new DefaultTableModel();
            // Se comienza.
            //creo el gestor persona
            GestorPerfil gp = new GestorPerfil();
            //obtengo las personas en base de datos
            List<Perfil> perfiles = gp.dameListaPerfiles();
            GestorTabla.anhadeFilasDeDatos(perfiles, listaPerfiles);
            //seteo el modelo de datos a la tablaCliente
            tablaPerfiles.setModel(listaPerfiles);
            //oculto el campo id de la tablaCliente
            tablaPerfiles.getColumnModel().removeColumn(tablaPerfiles.getColumnModel().getColumn(0));
            gp.cerrarConexion();

        } catch (Exception ex) {
            Logger.getLogger(perfil_lista_admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void configTabla() {
        listaPerfiles = new DefaultTableModel();
        listaPerfiles.addColumn("id");
        listaPerfiles.addColumn("Denominacion");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPerfiles = new javax.swing.JTable();
        btCerrar = new javax.swing.JButton();
        btSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPerfiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPerfiles);

        btCerrar.setText("Cerrar");
        btCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCerrarActionPerformed(evt);
            }
        });

        btSeleccionar.setText("Seleccionar");
        btSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeleccionarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(221, Short.MAX_VALUE)
                .add(btSeleccionar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(btCerrar)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btCerrar)
                    .add(btSeleccionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCerrarActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_btCerrarActionPerformed

private void btSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeleccionarActionPerformed
// TODO add your handling code here:
    int filaSeleccionada = tablaPerfiles.getSelectedRow();//numero fila seleccionada

    try {
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente de la lista", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            Long valorId = (Long) listaPerfiles.getValueAt(filaSeleccionada, 0);
            String denominacion = (String) listaPerfiles.getValueAt(filaSeleccionada, 1);
            usuarioAdmin.idPerfil = Long.toString(valorId);
            usuarioAdmin.denominacionPerfil = denominacion;
            usuarioAdmin.cargarPerfil();
            this.setVisible(false);

        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_btSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCerrar;
    private javax.swing.JButton btSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPerfiles;
    // End of variables declaration//GEN-END:variables
}
