/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Dimension;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author martin
 */
public class JF_Clientes extends javax.swing.JInternalFrame {


    /**
     * Creates new form JF_Clientes
     */
    public JF_Clientes() {
        initComponents();
    }

    public JButton getjB_Eliminar() {
        return jB_Eliminar;
    }

    public void setjB_Eliminar(JButton jB_Eliminar) {
        this.jB_Eliminar = jB_Eliminar;
    }

    public JButton getjB_Insetar() {
        return jB_Insetar;
    }

    public void setjB_Insetar(JButton jB_Insetar) {
        this.jB_Insetar = jB_Insetar;
    }

    public JButton getjB_Modificar() {
        return jB_Modificar;
    }

    public void setjB_Modificar(JButton jB_Modificar) {
        this.jB_Modificar = jB_Modificar;
    }

    public JButton getjB_VerTodos() {
        return jB_VerTodos;
    }

    public void setjB_VerTodos(JButton jB_VerTodos) {
        this.jB_VerTodos = jB_VerTodos;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JRadioButton getjR_Mujer() {
        return jR_Mujer;
    }

    public void setjR_Mujer(JRadioButton jR_Mujer) {
        this.jR_Mujer = jR_Mujer;
    }

    public JRadioButton getjR_Varon() {
        return jR_Varon;
    }

    public void setjR_Varon(JRadioButton jR_Varon) {
        this.jR_Varon = jR_Varon;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public ButtonGroup getjSexo() {
        return jSexo;
    }

    public void setjSexo(String jSexo) {
        if(jSexo.equals("Femenino")){
          this.jR_Mujer.setSelected(true); 
        }else if(jSexo.equals("Masculino")){
          this.jR_Varon.setSelected(true);   
        }
    }

    public JTextField getjT_Apellido() {
        return jT_Apellido;
    }

    public void setjT_Apellido(String jT_Apellido) {
        this.jT_Apellido.setText(jT_Apellido);
    }

    public JTextField getjT_Dni() {
        return jT_Dni;
    }

    public void setjT_Dni(String jT_DniString) {
        this.jT_Dni.setText(jT_DniString);
    }
    
    public void setjTextField_Dni(JTextField jT_Dni) {
        this.jT_Dni = jT_Dni;
    }

    public JTextField getjT_Nombre() {
        return jT_Nombre;
    }

    public void setjT_Nombre(String jT_Nombre) {
        this.jT_Nombre.setText(jT_Nombre); 
    }

    public JTextField getjT_Telefono() {
        return jT_Telefono;
    }

    public void setjT_Telefono(String jT_Telefono) {
        this.jT_Telefono.setText(jT_Telefono);
    }

    public JTable getjTable_Clientes() {
        return jTable_Clientes;
    }

    public void setjTable_Clientes(JTable jTable_Clientes) {
        this.jTable_Clientes = jTable_Clientes;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSexo = new javax.swing.ButtonGroup();
        jT_Dni = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jT_Nombre = new javax.swing.JTextField();
        jT_Apellido = new javax.swing.JTextField();
        jT_Telefono = new javax.swing.JTextField();
        jR_Mujer = new javax.swing.JRadioButton();
        jR_Varon = new javax.swing.JRadioButton();
        jB_Insetar = new javax.swing.JButton();
        jB_Modificar = new javax.swing.JButton();
        jB_Eliminar = new javax.swing.JButton();
        jB_VerTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Clientes = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Teléfono");

        jLabel4.setText("Sexo");

        jLabel5.setText("Dni");

        jSexo.add(jR_Mujer);
        jR_Mujer.setSelected(true);
        jR_Mujer.setText("Mujer");
        jR_Mujer.setActionCommand("F");

        jSexo.add(jR_Varon);
        jR_Varon.setText("Varón");
        jR_Varon.setActionCommand("M");

        jB_Insetar.setText("Insertar");

        jB_Modificar.setText("Modificar");

        jB_Eliminar.setText("Eliminar");

        jB_VerTodos.setText("Ver Todos");

        jTable_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_Clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jR_Mujer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jR_Varon))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jT_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jT_Apellido)
                            .addComponent(jT_Telefono)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_Insetar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_Modificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jB_VerTodos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_Dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jT_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jT_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jT_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jR_Mujer)
                    .addComponent(jR_Varon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_Insetar)
                    .addComponent(jB_Modificar)
                    .addComponent(jB_Eliminar)
                    .addComponent(jB_VerTodos))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_Eliminar;
    private javax.swing.JButton jB_Insetar;
    private javax.swing.JButton jB_Modificar;
    private javax.swing.JButton jB_VerTodos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jR_Mujer;
    private javax.swing.JRadioButton jR_Varon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup jSexo;
    private javax.swing.JTextField jT_Apellido;
    private javax.swing.JTextField jT_Dni;
    private javax.swing.JTextField jT_Nombre;
    private javax.swing.JTextField jT_Telefono;
    private javax.swing.JTable jTable_Clientes;
    // End of variables declaration//GEN-END:variables
}
