/*
 * persona_lista.java
 *
 * Created on 24 de agosto de 2009, 12:52
 */
package vista;

import controlador.GestorPersona;
import controlador.GestorTabla;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import modelo.Persona;

/**
 *
 * @author  0535
 */
public class persona_lista extends javax.swing.JFrame {

    private DefaultTableModel listaPersonas;

    /** Creates new form persona_lista */
    public persona_lista() {
        try {
            initComponents();
            //configuro el encabezado de la tabla
            configTabla();
            //modelo = new DefaultTableModel();
            // Se comienza.
            //creo el gestor persona
            GestorPersona gp = new GestorPersona();
            //obtengo las personas en base de datos
            List<Persona> personas = gp.dameListaPersonasHQL();
            GestorTabla.anhadeFilasDeDatos(personas, listaPersonas);
            //seteo el modelo de datos a la tablaCliente
            tabla_persona.setModel(listaPersonas);
            //oculto el campo id de la tablaCliente
            tabla_persona.getColumnModel().removeColumn(tabla_persona.getColumnModel().getColumn(0));
            tabla_persona.getColumnModel().removeColumn(tabla_persona.getColumnModel().getColumn(3));
            gp.cerrarConexion();

        } catch (Exception ex) {
            Logger.getLogger(persona_lista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void configTabla() {
        listaPersonas = new DefaultTableModel();
        listaPersonas.addColumn("id");
        listaPersonas.addColumn("Nombre");
        listaPersonas.addColumn("Apellido");
        listaPersonas.addColumn("DNI");
        listaPersonas.addColumn("iddomicilio");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_agregar = new javax.swing.JButton();
        bt_modificar = new javax.swing.JButton();
        bt_eliminar = new javax.swing.JButton();
        bt_cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_persona = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bt_agregar.setText("Agregar");
        bt_agregar.setFocusable(false);
        bt_agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_agregarActionPerformed(evt);
            }
        });

        bt_modificar.setText("Modificar");
        bt_modificar.setFocusable(false);
        bt_modificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_modificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_modificarActionPerformed(evt);
            }
        });

        bt_eliminar.setText("Eliminar");
        bt_eliminar.setFocusable(false);
        bt_eliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bt_eliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bt_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_eliminarActionPerformed(evt);
            }
        });

        bt_cerrar.setText("Cerrar");
        bt_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cerrarActionPerformed(evt);
            }
        });

        tabla_persona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_persona);

        jLabel1.setText("Apellido / Nombre");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1)
                    .add(layout.createSequentialGroup()
                        .add(bt_agregar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bt_modificar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(bt_eliminar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 141, Short.MAX_VALUE)
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(txtSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(3, 3, 3)
                        .add(jButton1))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(bt_cerrar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(bt_agregar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(bt_modificar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(bt_eliminar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(txtSearch, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jButton1)
                        .add(jLabel1)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bt_cerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void bt_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_modificarActionPerformed
// TODO add your handling code here:
    int filaSeleccionada = tabla_persona.getSelectedRow();//numero fila seleccionada

    int columnaSeleccionada = tabla_persona.getSelectedColumn();//numero de columna seleccionada NO ME INTERESA

    try {
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione un cliente de la lista", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            Long valorId = (Long) listaPersonas.getValueAt(filaSeleccionada, 0);
            System.out.println(valorId);//valor ID de la FILA


            new persona_admin(this, true, valorId).setVisible(true);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_bt_modificarActionPerformed

private void bt_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cerrarActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_bt_cerrarActionPerformed

private void bt_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_agregarActionPerformed
// TODO add your handling code here:
    new persona_admin(this, false, new Long(-1)).setVisible(true);

}//GEN-LAST:event_bt_agregarActionPerformed
    public void actualizarTabla() {
        GestorPersona gp = new GestorPersona();
        List<Persona> personas = gp.dameListaPersonas();
        GestorTabla.rellena(personas, listaPersonas);
        gp.cerrarConexion();
    }
private void bt_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_eliminarActionPerformed
// TODO add your handling code here:
    int filaSeleccionada = tabla_persona.getSelectedRow();
    int columnaSeleccionada = tabla_persona.getSelectedColumn();

    try {
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una persona de la lista", "Error", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            Long valorId = (Long) listaPersonas.getValueAt(filaSeleccionada, 0);
            System.out.println(valorId);

            GestorPersona gp = new GestorPersona();
            gp.eliminarPersonaFila(valorId);
            actualizarTabla();
            gp.cerrarConexion();
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
}//GEN-LAST:event_bt_eliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String valorBusqueda = txtSearch.getText();
            GestorPersona gp = new GestorPersona();
            List<Persona> personas = gp.getPersonasXNombreApellidoHQL(valorBusqueda);
            GestorTabla.rellena(personas, listaPersonas);
        
        } catch (Exception ex) {
            Logger.getLogger(persona_lista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_agregar;
    private javax.swing.JButton bt_cerrar;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_persona;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
